MAIN_FILE = Assn4-MM22B011

LATEX_COMPILER = pdflatex

all: $(MAIN_FILE).pdf

$(MAIN_FILE).pdf: $(MAIN_FILE).tex
	$(LATEX_COMPILER) $(MAIN_FILE).tex

clean:
	rm -f $(MAIN_FILE).aux $(MAIN_FILE).log $(MAIN_FILE).out

