target:ae22b110.tex Laplace,_Pierre-Simon,_marquis_de.jpg strip_lines.png
	pdflatex ae22b110.tex
	bibtex ae22b110	
	pdflatex ae22b110.tex
	pdflatex ae22b110.tex

	rm -f ae22b110.aux ae22b110.bbl ae22b110.log ae22b110.blg

