all: mm22b051.tex 1.eps ref.bib
	latex mm22b051.tex
	bibtex mm22b051.aux
	latex mm22b051.tex
	latex mm22b051.tex
	pdflatex mm22b051.tex
	rm -f mm22b051.aux mm22b051.bbl mm22b051.log mm22b051.dvi mm22b051.blg 1-eps-converted-to.pdf
